version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "0:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "0:3000"
    networks:
      - app-network
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000

networks:
  app-network:
    driver: bridge
